import type { Project } from "./types";

// Checked 2026-10-09 against AryaVora621/adhdsat at commit b1a494b: README, REBRAND.md, the
// route code in server/index.js, server/data/questions.json, src/pages/Sprint.jsx (the count-up
// timer per question, at most two hints, the keys 1 to 4, Enter and H), src/components/
// StrikeToggle.jsx (the cross-out button on each choice) and the screenshot committed to the
// repository (sprint-picker-v2.png). The repository is still named adhdsat; REBRAND.md records
// the rename to Tally on 2026-06-30. The question bank has 1,062 questions (567 Math, 495
// English); by their `source` field 912 are generated, 80 ingested and 70 authored.
//
// The cover is the app's own sprint screen, captured 2026-10-09 at 4x from a scratch clone with
// the dark theme on. The clone needed two local changes to run, and neither was committed
// anywhere: App.jsx calls a useEffect after its early returns, which throws React error 310 on
// load (the error number the deployed app shows, see below), so the hook was moved above them;
// and the cross-out buttons next to each answer take the global button padding, which hides
// their icon, so the padding was zeroed. The question is adv_048 in the bank, and /api was
// answered from server/data/questions.json instead of Postgres. The cover is cropped to the
// question, so the sidebar is out of it. It leads the page like every other cover, with the
// caption "A sprint question."; it is the only picture on the page, so no figure repeats it.
//
// The summary carries the sprint lengths, the weak-topic targeting, XP, streaks and the predicted
// score, so the first section opens on what a sprint question looks like and does not repeat them.
//
// Voice: the one first-person line is the timeline's first, built from the repository alone (its
// first commit is 2026-06-28). 127 of the repository's 185 commits carry a Co-Authored-By trailer
// for an AI agent (Claude or Google Antigravity), so no line says "I" made a particular change,
// and no role line is set: how the work was split is Arya's to say.
//
// No link to the deployed app: a fresh headless visit to adhdsat.vercel.app on 2026-10-09 landed
// on the app's own "Something went wrong" error screen (React error 310), so Arya should check
// it before the page points anywhere.
export const tally: Project = {
  slug: "tally",
  title: "Tally",
  category: "Software",
  tab: "Tally",
  year: "2026",
  status: "In development",
  summary:
    "Short sprints of 5, 10, 15 or 20 questions target the SAT topics a student is weakest in, and a spaced-repetition queue brings missed questions back. It adds XP, streaks and a predicted score, and an optional Gemini coach explains answers.",
  cover: {
    src: "/projects/tally-cover.webp",
    alt: "A Tally sprint question in the app’s dark theme, shown in grayscale: a progress bar of ten steps, a math question about the vertex of a parabola, four answer choices and Hint and Check Answer buttons.",
    width: 3200,
    height: 2000,
    caption: "A sprint question.",
    tint: true,
  },
  stack: ["React", "Vite", "Express", "Postgres"],
  links: [{ label: "Repository on GitHub", href: "https://github.com/AryaVora621/adhdsat" }],
  blocks: [
    {
      kind: "text",
      heading: "Practice in short sprints",
      body: [
        "Each sprint question shows a running timer and allows up to two hints, and every answer choice has a button that crosses it out. The keys 1 to 4 pick a choice, Enter checks the answer and H shows a hint.",
      ],
    },
    {
      kind: "text",
      heading: "Review gaps and the predicted score",
      body: [
        "A missed question goes into a review queue on the SM-2 schedule and comes back a day later. The first correct review keeps the gap at 1 day, the second sets it to 6, and each one after multiplies the last gap by 2.5. A wrong review sends the card back to 1 day.",
        "The predicted score appears after 10 answered questions. For Math and for English it weights the last 60 answers by difficulty, counting easy as 1, medium as 1.5 and hard as 2, maps the weighted accuracy onto 200 to 800, and shows the total with a range of 40 points either side.",
      ],
    },
    {
      kind: "text",
      heading: "How it is built",
      body: [
        "The question bank is a JSON file of 1,062 questions, 567 in Math and 495 in English, that seeds the database the first time the server boots. Most of them were generated by AI.",
        "The front end is React 19 with Vite, and the API is Express 5, which also runs as a Vercel serverless function. Progress lives in its own schema in Supabase Postgres. Without a Gemini key, the difficulty targeting and the coach’s insights fall back to fixed rules; answer explanations and score-report import need the key.",
      ],
    },
    {
      kind: "specs",
      heading: "Features",
      rows: [
        {
          label: "Practice",
          value: "Sprints, a review queue, full timed practice tests and a study plan with a target score and test date",
        },
        {
          label: "Mobile",
          value:
            "A Capacitor Android project is scaffolded in `android/`. The plan in the repository lists the iOS build as waiting on Xcode.",
        },
      ],
    },
    {
      kind: "timeline",
      heading: "Timeline",
      items: [
        { date: "2026-06-28", text: "I started the repository as ADHDSat, the name it still has." },
        { date: "2026-06-30", text: "The rename to Tally was decided and recorded in `REBRAND.md`." },
        { date: "2026-09", text: "My Focus and My Drills pages joined the sidebar." },
      ],
    },
  ],
};
