// Fetches Arya's real public GitHub data and bakes it into src/data/github.ts.
// Run: npm run data:github (or: node scripts/fetch-github.mjs)
// Unauthenticated GitHub API limit is 60 req/hr; this script uses ~45 without
// GITHUB_TOKEN. With a token it also reads last-commit dates (~90 requests).
const USER = "AryaVora621";
const OUT = new URL("../src/data/github.ts", import.meta.url);
const token = process.env.GITHUB_TOKEN;

const anonymousHeaders = {
  Accept: "application/vnd.github+json",
  "User-Agent": "arya-vora.org-data-pipeline",
};
const headers = {
  ...anonymousHeaders,
  ...(token ? { Authorization: `Bearer ${token}` } : {}),
};

async function get(url) {
  let res = await fetch(url, { headers });
  // The openultracode org refuses long-lived fine-grained tokens with a 403.
  // Its public data is still readable anonymously, so retry once without one.
  if (res.status === 403 && token) res = await fetch(url, { headers: anonymousHeaders });
  if (!res.ok) throw new Error(`GET ${url} -> ${res.status}`);
  return res.json();
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

const profile = await get(`https://api.github.com/users/${USER}`);

let repos = [];
let page = 1;
for (;;) {
  const batch = await get(
    `https://api.github.com/users/${USER}/repos?per_page=100&page=${page}&type=all`
  );
  if (!Array.isArray(batch) || batch.length === 0) break;
  repos.push(...batch);
  if (batch.length < 100) break;
  page += 1;
}

const own = repos.filter((r) => !r.fork);
const owned = own.filter((r) => r.owner?.login === USER);
const member = own.filter((r) => r.owner?.login !== USER);

// Aggregate real language bytes across owned + member repos
// (empty repos contribute nothing, so skip them).
const languageBytes = {};
const withCode = own.filter((r) => r.size > 0);
const unavailableLanguages = [];
for (const repo of withCode) {
  try {
    const langs = await get(repo.languages_url);
    for (const [lang, bytes] of Object.entries(langs)) {
      languageBytes[lang] = (languageBytes[lang] ?? 0) + bytes;
    }
  } catch (err) {
    unavailableLanguages.push(repo.full_name);
    console.warn(`skip languages for ${repo.name}: ${err.message}`);
  }
  await sleep(150);
}

// Recent public pushes. Only read by the unmounted src/components/sections/Projects.tsx; drop with that file.
let recentActivity = [];
try {
  const events = await get(`https://api.github.com/users/${USER}/events/public?per_page=30`);
  recentActivity = events
    .filter((e) => e.type === "PushEvent")
    .slice(0, 8)
    .map((e) => ({
      repo: e.repo.name.replace(`${USER}/`, ""),
      date: e.created_at.slice(0, 10),
      commits: e.payload?.commits?.length ?? 0,
      message: e.payload?.commits?.[0]?.message?.split("\n")[0]?.slice(0, 90) ?? "",
    }));
} catch (err) {
  console.warn(`skip events: ${err.message}`);
}

// Date of the newest commit on each default branch. pushed_at also moves when a
// bot pushes some other branch (Dependabot does this on openultracode), so the
// projects list shows this date as "Last commit" and falls back to pushedAt.
const lastCommits = {};
if (token) {
  for (const repo of withCode) {
    try {
      const branch = encodeURIComponent(repo.default_branch);
      const [head] = await get(`${repo.url}/commits?per_page=1&sha=${branch}`);
      if (head) lastCommits[repo.full_name] = head.commit.committer.date.slice(0, 10);
    } catch (err) {
      console.warn(`skip last commit for ${repo.name}: ${err.message}`);
    }
    await sleep(100);
  }
} else {
  console.warn("no GITHUB_TOKEN, so last-commit dates are skipped to stay under the anonymous limit");
}

const pick = (r) => ({
  name: r.name,
  owner: r.owner?.login ?? USER,
  description: r.description ?? "",
  language: r.language,
  stars: r.stargazers_count,
  url: r.html_url,
  pushedAt: r.pushed_at.slice(0, 10),
  lastCommit: lastCommits[r.full_name] ?? null,
  empty: r.size === 0,
});

const data = {
  profile: {
    login: profile.login,
    name: profile.name,
    url: profile.html_url,
    avatar: profile.avatar_url,
    publicRepos: profile.public_repos,
    followers: profile.followers,
    following: profile.following,
    createdAt: profile.created_at.slice(0, 10),
  },
  totalStars: own.reduce((n, r) => n + r.stargazers_count, 0),
  languageBytes: Object.fromEntries(
    Object.entries(languageBytes).sort((a, b) => b[1] - a[1])
  ),
  languageCoverage: {
    requested: withCode.length,
    fetched: withCode.length - unavailableLanguages.length,
    unavailable: unavailableLanguages,
  },
  repos: own.map(pick).sort((a, b) => (a.pushedAt < b.pushedAt ? 1 : -1)),
  ownedCount: owned.length,
  memberRepos: member.map((r) => r.full_name),
  recentActivity,
  fetchedAt: new Date().toISOString().slice(0, 10),
};

const ts = `// AUTO-GENERATED by scripts/fetch-github.mjs. Do not edit by hand.
// Refresh: npm run data:github (needs GitHub API quota). Snapshot: ${data.fetchedAt}.
export const github = ${JSON.stringify(data, null, 2)} as const;

export type GithubRepo = (typeof github.repos)[number];
`;

await import("node:fs/promises").then((fs) => fs.writeFile(OUT, ts));
console.log(
  `wrote src/data/github.ts: ${own.length} repos, ${Object.keys(languageBytes).length} languages, ${recentActivity.length} recent pushes`
);
