// Fetches Arya's real public GitHub data and bakes it into src/data/github.ts.
// Run: npm run data:github (or: node scripts/fetch-github.mjs)
// Unauthenticated GitHub API limit is 60 req/hr; this script uses ~45.
const USER = "AryaVora621";
const OUT = new URL("../src/data/github.ts", import.meta.url);

const headers = {
  Accept: "application/vnd.github+json",
  "User-Agent": "aryavora.com-data-pipeline",
  ...(process.env.GITHUB_TOKEN ? { Authorization: `Bearer ${process.env.GITHUB_TOKEN}` } : {}),
};

async function get(url) {
  const res = await fetch(url, { headers });
  if (!res.ok) throw new Error(`GET ${url} -> ${res.status}`);
  return res.json();
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

const profile = await get(`https://api.github.com/users/${USER}`);

let repos = [];
let page = 1;
for (;;) {
  const batch = await get(
    `https://api.github.com/users/${USER}/repos?per_page=100&page=${page}&type=all`
  );
  if (!Array.isArray(batch) || batch.length === 0) break;
  repos.push(...batch);
  if (batch.length < 100) break;
  page += 1;
}

const own = repos.filter((r) => !r.fork);
const owned = own.filter((r) => r.owner?.login === USER);
const member = own.filter((r) => r.owner?.login !== USER);

// Aggregate real language bytes across owned + member repos
// (empty repos contribute nothing — skip them).
const languageBytes = {};
const withCode = own.filter((r) => r.size > 0);
for (const repo of withCode) {
  try {
    const langs = await get(repo.languages_url);
    for (const [lang, bytes] of Object.entries(langs)) {
      languageBytes[lang] = (languageBytes[lang] ?? 0) + bytes;
    }
  } catch (err) {
    console.warn(`skip languages for ${repo.name}: ${err.message}`);
  }
  await sleep(150);
}

// Recent public activity (pushes) — powers the "recently" shelf.
let recentActivity = [];
try {
  const events = await get(`https://api.github.com/users/${USER}/events/public?per_page=30`);
  recentActivity = events
    .filter((e) => e.type === "PushEvent")
    .slice(0, 8)
    .map((e) => ({
      repo: e.repo.name.replace(`${USER}/`, ""),
      date: e.created_at.slice(0, 10),
      commits: e.payload?.commits?.length ?? 0,
      message: e.payload?.commits?.[0]?.message?.split("\n")[0]?.slice(0, 90) ?? "",
    }));
} catch (err) {
  console.warn(`skip events: ${err.message}`);
}

const pick = (r) => ({
  name: r.name,
  owner: r.owner?.login ?? USER,
  description: r.description ?? "",
  language: r.language,
  stars: r.stargazers_count,
  url: r.html_url,
  pushedAt: r.pushed_at.slice(0, 10),
  empty: r.size === 0,
});

const data = {
  profile: {
    login: profile.login,
    name: profile.name,
    url: profile.html_url,
    avatar: profile.avatar_url,
    publicRepos: profile.public_repos,
    followers: profile.followers,
    following: profile.following,
    createdAt: profile.created_at.slice(0, 10),
  },
  totalStars: own.reduce((n, r) => n + r.stargazers_count, 0),
  languageBytes: Object.fromEntries(
    Object.entries(languageBytes).sort((a, b) => b[1] - a[1])
  ),
  repos: own.map(pick).sort((a, b) => (a.pushedAt < b.pushedAt ? 1 : -1)),
  ownedCount: owned.length,
  memberRepos: member.map((r) => r.full_name),
  recentActivity,
  fetchedAt: new Date().toISOString().slice(0, 10),
};

const ts = `// AUTO-GENERATED by scripts/fetch-github.mjs — do not edit by hand.
// Refresh: npm run data:github (needs GitHub API quota). Snapshot: ${data.fetchedAt}.
export const github = ${JSON.stringify(data, null, 2)} as const;

export type GithubRepo = (typeof github.repos)[number];
`;

await import("node:fs/promises").then((fs) => fs.writeFile(OUT, ts));
console.log(
  `wrote src/data/github.ts — ${own.length} repos, ${Object.keys(languageBytes).length} languages, ${recentActivity.length} recent pushes`
);
