// AUTO-GENERATED by scripts/fetch-github.mjs. Do not edit by hand.
// Refresh: npm run data:github (needs GitHub API quota). Snapshot: 2026-10-08.
export const github = {
  "profile": {
    "login": "AryaVora621",
    "name": "Arya Vora",
    "url": "https://github.com/AryaVora621",
    "avatar": "https://avatars.githubusercontent.com/u/147209880?v=4",
    "publicRepos": 44,
    "followers": 0,
    "following": 0,
    "createdAt": "2023-10-06"
  },
  "totalStars": 0,
  "languageBytes": {
    "Python": 5781422,
    "MDX": 4635630,
    "TypeScript": 3303426,
    "HTML": 1242624,
    "JavaScript": 807380,
    "CSS": 181459,
    "Shell": 128017,
    "Swift": 48436,
    "Java": 43161,
    "C++": 30931,
    "PLpgSQL": 30657,
    "Nix": 15459,
    "Batchfile": 5232,
    "PowerShell": 3599,
    "Dockerfile": 3552,
    "Assembly": 642
  },
  "languageCoverage": {
    "requested": 41,
    "fetched": 41,
    "unavailable": []
  },
  "repos": [
    {
      "name": "aryavora.com",
      "owner": "AryaVora621",
      "description": "Personal portfolio and engineering experiments showcase built with Next.js 15, Three.js, and smooth physics interactions",
      "language": "TypeScript",
      "stars": 0,
      "url": "https://github.com/AryaVora621/aryavora.com",
      "pushedAt": "2026-10-08",
      "lastCommit": "2026-10-08",
      "empty": false
    },
    {
      "name": "ourPage",
      "owner": "AryaVora621",
      "description": "",
      "language": "TypeScript",
      "stars": 0,
      "url": "https://github.com/AryaVora621/ourPage",
      "pushedAt": "2026-10-02",
      "lastCommit": "2026-10-02",
      "empty": false
    },
    {
      "name": "AryaVora621",
      "owner": "AryaVora621",
      "description": "Special repository for Arya Vora's GitHub profile README",
      "language": null,
      "stars": 0,
      "url": "https://github.com/AryaVora621/AryaVora621",
      "pushedAt": "2026-09-15",
      "lastCommit": "2026-09-15",
      "empty": false
    },
    {
      "name": "SmartInvest",
      "owner": "AryaVora621",
      "description": "Fintech research dashboard for Indian (NSE/BSE) and US stocks with curated emerging markets screener",
      "language": "TypeScript",
      "stars": 0,
      "url": "https://github.com/AryaVora621/SmartInvest",
      "pushedAt": "2026-09-14",
      "lastCommit": "2026-09-13",
      "empty": false
    },
    {
      "name": "m.i.r.a",
      "owner": "AryaVora621",
      "description": "Interactive room assistant with sub-pixel ArUco projector auto-homography calibration (0.0px error) and Rust daemon",
      "language": null,
      "stars": 0,
      "url": "https://github.com/AryaVora621/m.i.r.a",
      "pushedAt": "2026-09-14",
      "lastCommit": "2026-08-17",
      "empty": false
    },
    {
      "name": "drone",
      "owner": "AryaVora621",
      "description": "Custom ESP32 QuadX drone flight controller firmware and handheld ESP-NOW 2.4GHz joystick transmitter",
      "language": "Python",
      "stars": 0,
      "url": "https://github.com/AryaVora621/drone",
      "pushedAt": "2026-09-14",
      "lastCommit": "2026-09-14",
      "empty": false
    },
    {
      "name": "adhdsat",
      "owner": "AryaVora621",
      "description": "",
      "language": "JavaScript",
      "stars": 0,
      "url": "https://github.com/AryaVora621/adhdsat",
      "pushedAt": "2026-09-14",
      "lastCommit": "2026-09-13",
      "empty": false
    },
    {
      "name": "openultracode",
      "owner": "openultracode",
      "description": "Local CLI for parallel coding agents with adaptive model routing.",
      "language": "TypeScript",
      "stars": 0,
      "url": "https://github.com/openultracode/openultracode",
      "pushedAt": "2026-09-07",
      "lastCommit": "2026-06-06",
      "empty": false
    },
    {
      "name": "claude-agy",
      "owner": "AryaVora621",
      "description": "",
      "language": "Python",
      "stars": 0,
      "url": "https://github.com/AryaVora621/claude-agy",
      "pushedAt": "2026-09-06",
      "lastCommit": "2026-09-06",
      "empty": false
    },
    {
      "name": "nana-ebook-reader",
      "owner": "AryaVora621",
      "description": "Offline accessibility book reader on Raspberry Pi Zero 2W with OpenCV, Tesseract OCR, and Piper Neural TTS",
      "language": "Python",
      "stars": 0,
      "url": "https://github.com/AryaVora621/nana-ebook-reader",
      "pushedAt": "2026-08-09",
      "lastCommit": "2026-08-09",
      "empty": false
    },
    {
      "name": "claudeshorts",
      "owner": "AryaVora621",
      "description": "",
      "language": "Python",
      "stars": 0,
      "url": "https://github.com/AryaVora621/claudeshorts",
      "pushedAt": "2026-07-14",
      "lastCommit": "2026-07-14",
      "empty": false
    },
    {
      "name": "orochi",
      "owner": "AryaVora621",
      "description": "Multi-tool CoreXY 3D printer evolution built on an Ender 5 Pro with Klipper and StealthChanger",
      "language": null,
      "stars": 0,
      "url": "https://github.com/AryaVora621/orochi",
      "pushedAt": "2026-07-13",
      "lastCommit": "2026-07-13",
      "empty": false
    },
    {
      "name": "smartAI",
      "owner": "AryaVora621",
      "description": "",
      "language": "Python",
      "stars": 0,
      "url": "https://github.com/AryaVora621/smartAI",
      "pushedAt": "2026-07-12",
      "lastCommit": "2026-07-12",
      "empty": false
    },
    {
      "name": "roboPet",
      "owner": "AryaVora621",
      "description": "",
      "language": "Python",
      "stars": 0,
      "url": "https://github.com/AryaVora621/roboPet",
      "pushedAt": "2026-07-11",
      "lastCommit": "2026-07-11",
      "empty": false
    },
    {
      "name": "freeGPT",
      "owner": "AryaVora621",
      "description": "",
      "language": "Python",
      "stars": 0,
      "url": "https://github.com/AryaVora621/freeGPT",
      "pushedAt": "2026-07-10",
      "lastCommit": "2026-07-10",
      "empty": false
    },
    {
      "name": "memgine",
      "owner": "AryaVora621",
      "description": "",
      "language": "TypeScript",
      "stars": 0,
      "url": "https://github.com/AryaVora621/memgine",
      "pushedAt": "2026-07-04",
      "lastCommit": "2026-07-04",
      "empty": false
    },
    {
      "name": "openpeers",
      "owner": "AryaVora621",
      "description": "",
      "language": "TypeScript",
      "stars": 0,
      "url": "https://github.com/AryaVora621/openpeers",
      "pushedAt": "2026-07-01",
      "lastCommit": "2026-07-01",
      "empty": false
    },
    {
      "name": "isc",
      "owner": "AryaVora621",
      "description": "",
      "language": "HTML",
      "stars": 0,
      "url": "https://github.com/AryaVora621/isc",
      "pushedAt": "2026-06-24",
      "lastCommit": "2026-06-24",
      "empty": false
    },
    {
      "name": "adDesign",
      "owner": "AryaVora621",
      "description": "",
      "language": null,
      "stars": 0,
      "url": "https://github.com/AryaVora621/adDesign",
      "pushedAt": "2026-06-21",
      "lastCommit": null,
      "empty": true
    },
    {
      "name": "opcodestockapp",
      "owner": "kb27app-beep",
      "description": "",
      "language": "HTML",
      "stars": 0,
      "url": "https://github.com/kb27app-beep/opcodestockapp",
      "pushedAt": "2026-06-20",
      "lastCommit": "2026-06-19",
      "empty": false
    },
    {
      "name": "stock-research-app",
      "owner": "bj1960-del",
      "description": "Indian Stock Research & Portfolio Management App",
      "language": "TypeScript",
      "stars": 0,
      "url": "https://github.com/bj1960-del/stock-research-app",
      "pushedAt": "2026-06-20",
      "lastCommit": "2026-06-20",
      "empty": false
    },
    {
      "name": "GuideToCivilization",
      "owner": "AryaVora621",
      "description": "",
      "language": "MDX",
      "stars": 0,
      "url": "https://github.com/AryaVora621/GuideToCivilization",
      "pushedAt": "2026-06-17",
      "lastCommit": "2026-06-17",
      "empty": false
    },
    {
      "name": "freewillai",
      "owner": "AryaVora621",
      "description": "",
      "language": "Python",
      "stars": 0,
      "url": "https://github.com/AryaVora621/freewillai",
      "pushedAt": "2026-06-09",
      "lastCommit": "2026-06-09",
      "empty": false
    },
    {
      "name": "mediapad",
      "owner": "AryaVora621",
      "description": "Github repo for my stardance inspired media controller + visualizer",
      "language": "HTML",
      "stars": 0,
      "url": "https://github.com/AryaVora621/mediapad",
      "pushedAt": "2026-06-07",
      "lastCommit": "2026-06-07",
      "empty": false
    },
    {
      "name": "temp-email-tester",
      "owner": "AryaVora621",
      "description": "",
      "language": "TypeScript",
      "stars": 0,
      "url": "https://github.com/AryaVora621/temp-email-tester",
      "pushedAt": "2026-06-06",
      "lastCommit": "2026-06-06",
      "empty": false
    },
    {
      "name": "notchTerm",
      "owner": "AryaVora621",
      "description": "a visualizer for macbooks to view your terminals at a quick glance",
      "language": "Swift",
      "stars": 0,
      "url": "https://github.com/AryaVora621/notchTerm",
      "pushedAt": "2026-06-06",
      "lastCommit": "2026-06-06",
      "empty": false
    },
    {
      "name": "makeminds-site",
      "owner": "AryaVora621",
      "description": "Rebuild of makemindsrobotics.org — FTC Team 23786. Dark, motion-heavy, scroll-driven. Currently in planning.",
      "language": "TypeScript",
      "stars": 0,
      "url": "https://github.com/AryaVora621/makeminds-site",
      "pushedAt": "2026-05-23",
      "lastCommit": "2026-05-23",
      "empty": false
    },
    {
      "name": "loopCLI",
      "owner": "AryaVora621",
      "description": "",
      "language": null,
      "stars": 0,
      "url": "https://github.com/AryaVora621/loopCLI",
      "pushedAt": "2026-05-07",
      "lastCommit": "2026-05-07",
      "empty": false
    },
    {
      "name": "aryavora",
      "owner": "AryaVora621",
      "description": "",
      "language": "TypeScript",
      "stars": 0,
      "url": "https://github.com/AryaVora621/aryavora",
      "pushedAt": "2026-04-11",
      "lastCommit": "2026-04-11",
      "empty": false
    },
    {
      "name": "openguessr",
      "owner": "AryaVora621",
      "description": "",
      "language": "TypeScript",
      "stars": 0,
      "url": "https://github.com/AryaVora621/openguessr",
      "pushedAt": "2026-04-10",
      "lastCommit": "2026-04-10",
      "empty": false
    },
    {
      "name": "multiagent-showcase-openai-live",
      "owner": "AryaVora621",
      "description": "Multi-agent showcase with OpenAI live SSE integration",
      "language": "JavaScript",
      "stars": 0,
      "url": "https://github.com/AryaVora621/multiagent-showcase-openai-live",
      "pushedAt": "2026-04-05",
      "lastCommit": "2026-04-05",
      "empty": false
    },
    {
      "name": "shipkit",
      "owner": "AryaVora621",
      "description": "Production-readiness scanner and deployment workflow for AI-built apps",
      "language": "TypeScript",
      "stars": 0,
      "url": "https://github.com/AryaVora621/shipkit",
      "pushedAt": "2026-03-31",
      "lastCommit": "2026-03-31",
      "empty": false
    },
    {
      "name": "bizos-ecosystem",
      "owner": "AryaVora621",
      "description": "",
      "language": null,
      "stars": 0,
      "url": "https://github.com/AryaVora621/bizos-ecosystem",
      "pushedAt": "2026-03-30",
      "lastCommit": null,
      "empty": true
    },
    {
      "name": "recieptthingsy",
      "owner": "m0narch810",
      "description": "",
      "language": null,
      "stars": 0,
      "url": "https://github.com/m0narch810/recieptthingsy",
      "pushedAt": "2026-03-29",
      "lastCommit": null,
      "empty": true
    },
    {
      "name": "adgen-app",
      "owner": "AryaVora621",
      "description": "",
      "language": "TypeScript",
      "stars": 0,
      "url": "https://github.com/AryaVora621/adgen-app",
      "pushedAt": "2026-03-29",
      "lastCommit": "2026-03-29",
      "empty": false
    },
    {
      "name": "Arya-Vora-Landing-Page",
      "owner": "AryaVora621",
      "description": "",
      "language": "TypeScript",
      "stars": 0,
      "url": "https://github.com/AryaVora621/Arya-Vora-Landing-Page",
      "pushedAt": "2026-03-28",
      "lastCommit": "2026-03-28",
      "empty": false
    },
    {
      "name": "LocalMem",
      "owner": "AryaVora621",
      "description": "",
      "language": "Shell",
      "stars": 0,
      "url": "https://github.com/AryaVora621/LocalMem",
      "pushedAt": "2026-03-20",
      "lastCommit": "2026-03-20",
      "empty": false
    },
    {
      "name": "ftc-decode-scouting",
      "owner": "AryaVora621",
      "description": "",
      "language": "TypeScript",
      "stars": 0,
      "url": "https://github.com/AryaVora621/ftc-decode-scouting",
      "pushedAt": "2026-03-14",
      "lastCommit": "2026-03-14",
      "empty": false
    },
    {
      "name": "MakEMindsOutreach",
      "owner": "AryaVora621",
      "description": "",
      "language": "Java",
      "stars": 0,
      "url": "https://github.com/AryaVora621/MakEMindsOutreach",
      "pushedAt": "2026-01-08",
      "lastCommit": "2026-01-08",
      "empty": false
    },
    {
      "name": "backupvision",
      "owner": "AryaVora621",
      "description": "",
      "language": null,
      "stars": 0,
      "url": "https://github.com/AryaVora621/backupvision",
      "pushedAt": "2025-07-25",
      "lastCommit": null,
      "empty": true
    },
    {
      "name": "dynamicBlogPage",
      "owner": "AryaVora621",
      "description": "",
      "language": "TypeScript",
      "stars": 0,
      "url": "https://github.com/AryaVora621/dynamicBlogPage",
      "pushedAt": "2025-07-03",
      "lastCommit": "2025-07-03",
      "empty": false
    },
    {
      "name": "TeamStat-Insights",
      "owner": "AryaVora621",
      "description": "FTC match scouting and predictive team analytics platform built for FIRST Tech Challenge Team 23786 MakEMinds",
      "language": "TypeScript",
      "stars": 0,
      "url": "https://github.com/AryaVora621/TeamStat-Insights",
      "pushedAt": "2025-05-25",
      "lastCommit": "2025-05-25",
      "empty": false
    },
    {
      "name": "MakEMinds-Documentation",
      "owner": "AryaVora621",
      "description": "",
      "language": "JavaScript",
      "stars": 0,
      "url": "https://github.com/AryaVora621/MakEMinds-Documentation",
      "pushedAt": "2025-03-01",
      "lastCommit": "2025-03-01",
      "empty": false
    },
    {
      "name": "RedoAI",
      "owner": "AryaVora621",
      "description": "",
      "language": "Python",
      "stars": 0,
      "url": "https://github.com/AryaVora621/RedoAI",
      "pushedAt": "2024-11-14",
      "lastCommit": "2024-11-14",
      "empty": false
    },
    {
      "name": "PdfToBrainrot",
      "owner": "AryaVora621",
      "description": "",
      "language": null,
      "stars": 0,
      "url": "https://github.com/AryaVora621/PdfToBrainrot",
      "pushedAt": "2024-11-14",
      "lastCommit": null,
      "empty": true
    },
    {
      "name": "AI",
      "owner": "AryaVora621",
      "description": "",
      "language": "HTML",
      "stars": 0,
      "url": "https://github.com/AryaVora621/AI",
      "pushedAt": "2024-11-14",
      "lastCommit": "2024-11-14",
      "empty": false
    }
  ],
  "ownedCount": 42,
  "memberRepos": [
    "bj1960-del/stock-research-app",
    "kb27app-beep/opcodestockapp",
    "m0narch810/recieptthingsy",
    "openultracode/openultracode"
  ],
  "recentActivity": [
    {
      "repo": "aryavora.com",
      "date": "2026-10-08",
      "commits": 0,
      "message": ""
    },
    {
      "repo": "aryavora.com",
      "date": "2026-10-08",
      "commits": 0,
      "message": ""
    },
    {
      "repo": "aryavora.com",
      "date": "2026-10-08",
      "commits": 0,
      "message": ""
    },
    {
      "repo": "ourPage",
      "date": "2026-10-02",
      "commits": 0,
      "message": ""
    },
    {
      "repo": "AryaVora621",
      "date": "2026-09-15",
      "commits": 0,
      "message": ""
    },
    {
      "repo": "SmartInvest",
      "date": "2026-09-14",
      "commits": 0,
      "message": ""
    },
    {
      "repo": "drone",
      "date": "2026-09-14",
      "commits": 0,
      "message": ""
    },
    {
      "repo": "AryaVora621",
      "date": "2026-09-15",
      "commits": 0,
      "message": ""
    }
  ],
  "fetchedAt": "2026-10-08"
} as const;

export type GithubRepo = (typeof github.repos)[number];
